### ISSUE TITLE
Importing mods through Explorer window crashes the game.

### ISSUE THREAD

**Issue by Subsonic154** [Saiyan197/Kami-Modpack-Builder#1]
Pretty self-explanatory, Trying to import ANY mod, doesn't matter what it is through the Explorer window will cause the game to crash on startup with a "Exception type DSI occurred!" crash dump. This is a big issue because there doesen't seem to be any other way to add skins for the final smash characters (Giga Bowser, Mega Lucario, etc.) or to add script (animcmd) mods either without it.

**Comment by Subsonic154** [comment]
I forgot to mention that all mods added through the Character Mods tab work just fine. I haven't tested any Stage Mods or General Mods though.

**Comment by CosmewGH** [comment]
Thanks for reporting this. I haven't really used the explorer tab for mods personally so this slipped by me. I'll work on a fix.
In the meantime, you actually CAN modify any of the other misc things like final smash characters by using the General Mods tab. The general mods tab is meant for that stuff.

**Comment by Subsonic154** [comment]
Also another thing, Probably slightly off-topic from this bug but the Import General Mod in the Character Mods tab doesn't work. The UI lets you import it into the project but when you go into the Mods folder in the applications files the newly "imported" mod isn't there, And trying to delete it in the application throws a Null Reference Exception and won't let you delete it, So now you are stuck with a function-less mod in that characters tab forever. And yes, I used the correct folder naming system the UI told me to use. I'll try using that General Mods tab and see if i can import my custom effect.bin i downloaded for Samus (Dark Samus Phazon GFX).

**Comment by CosmewGH** [comment]
Ok that one's really interesting. I'll be able to work on it here soon. If I fix it I'll probably post an update.

**Comment by Subsonic154** [comment]
Alright! Adding mods through that General Mods tab works perfectly! Which means i can literally modify any game file in the data folder now, Sure you still have to rename a bunch of files just like you would when using Sm4shExplorer, But it's better because you can have all your mods displayed as a list with custom names so you never lose track of them. Imo once all the bugs get worked out this will replace Meteor and Sm4shExplorer.

**Comment by CosmewGH** [comment]
Alright, I found and fixed all the issues you told me about. Please give the new version a try!

**Comment by Subsonic154** [comment]
New version works perfectly! It's much easier to just add general mods through the Explorer window than the General Mods tab, At least for me anyways because i work in Sm4shExplorer a lot. Although the General Mods tab will still have it's uses, For example having a mod that you want to be toggle-able so you don't have to add it from the Explorer again if you make a new modpack.
